[project]
name = "parallel-py"
version = "0.1.1"
description = ""
authors = [
    {name = "rockov78",email = "rafael.chavesnovoa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "parallel_py", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
